
load "io".

try
    let i = 10/0.
    println i.
catch Exception(_, v) do
    println v.
end 
